"""Word bank for the daily mini crossword.

Every entry is a common English word paired with a short, plain clue. The grid
filler only ever uses words from here, so every generated puzzle is solvable
with clues that actually make sense.
"""

CLUES = {
    # --- 3 letters ---
    "AGE": "Number of years old",
    "AIR": "What you breathe",
    "ANT": "Picnic pest",
    "ARM": "Shoulder to hand",
    "ART": "Museum display",
    "BAG": "Grocery carrier",
    "BAT": "Baseball swinger",
    "BED": "Where you sleep",
    "BEE": "Hive dweller",
    "BOX": "Cardboard container",
    "BUS": "Public transit ride",
    "CAB": "Yellow city car",
    "CAP": "Bottle topper",
    "CAR": "Driveway sight",
    "CAT": "Purring pet",
    "COW": "Milk producer",
    "CUP": "Coffee holder",
    "DAY": "24 hours",
    "DOG": "Barking pet",
    "EAR": "Hearing organ",
    "EGG": "Breakfast staple",
    "END": "Final part",
    "EYE": "Seeing organ",
    "FAN": "Cooling device",
    "FOG": "Low cloud",
    "FOX": "Bushy-tailed wild dog",
    "GAS": "Pump purchase",
    "GEM": "Polished stone",
    "HAT": "Head cover",
    "HEN": "Egg layer",
    "ICE": "Frozen water",
    "INK": "Pen filler",
    "JAR": "Jam holder",
    "JAW": "Chin's bone",
    "JET": "Fast plane",
    "JOB": "Paid work",
    "KEY": "Lock opener",
    "KID": "Youngster",
    "LAB": "Science room",
    "LAW": "Rule on the books",
    "LEG": "Knee's limb",
    "LID": "Pot cover",
    "LIP": "Mouth edge",
    "LOG": "Fireplace piece",
    "MAP": "Road guide",
    "MAT": "Door greeter",
    "MUD": "Wet dirt",
    "MUG": "Handled cup",
    "NET": "Tennis divider",
    "NUT": "Bolt's partner",
    "OAK": "Acorn tree",
    "OIL": "Engine lubricant",
    "OWL": "Nighttime hooter",
    "PAN": "Frying dish",
    "PEA": "Small green vegetable",
    "PEN": "Ink writer",
    "PET": "Household animal",
    "PIE": "Sliced dessert",
    "PIG": "Farm oinker",
    "PIN": "Sewing spike",
    "POT": "Cooking vessel",
    "RAT": "Long-tailed rodent",
    "RIB": "Chest bone",
    "ROD": "Fishing pole",
    "ROW": "Line of seats",
    "RUG": "Floor covering",
    "SEA": "Salty expanse",
    "SET": "Matching group",
    "SKI": "Slope glider",
    "SKY": "Where clouds are",
    "SON": "Male child",
    "SPA": "Massage place",
    "SUN": "Daytime star",
    "TAG": "Price sticker",
    "TAX": "Government levy",
    "TEA": "Steeped drink",
    "TIE": "Neck accessory",
    "TIN": "Cookie container",
    "TIP": "Waiter's extra",
    "TOE": "Foot digit",
    "TOP": "Highest point",
    "TOY": "Plaything",
    "TUB": "Bath basin",
    "VAN": "Delivery vehicle",
    "VET": "Animal doctor",
    "WAR": "Armed conflict",
    "WAX": "Candle material",
    "WEB": "Spider's work",
    "WIG": "Fake hair",
    "ZOO": "Animal park",
    "BAD": "Not good",
    "BIG": "Large",
    "BIT": "Small piece",
    "BOY": "Young male",
    "BUD": "Flower before it opens",
    "BUG": "Creepy crawler",
    "BUN": "Burger bread",
    "BUY": "Purchase",
    "CRY": "Shed tears",
    "CUT": "Slice",
    "DAD": "Father",
    "DEN": "Cozy room",
    "DIG": "Use a shovel",
    "DOT": "Small round mark",
    "DRY": "Not wet",
    "EAT": "Have a meal",
    "FAR": "Distant",
    "FAT": "Not lean",
    "FEW": "Not many",
    "FIG": "Newton's fruit",
    "FIT": "In good shape",
    "FIX": "Repair",
    "FLY": "Travel by air",
    "FUN": "Good times",
    "FUR": "Animal coat",
    "GAP": "Space between",
    "GET": "Obtain",
    "GYM": "Workout spot",
    "HIP": "Side of the waist",
    "HIT": "Strike",
    "HOP": "Bunny move",
    "HOT": "Very warm",
    "HOW": "In what way",
    "HUB": "Center of activity",
    "HUG": "Warm squeeze",
    "ILL": "Sick",
    "JAM": "Toast topping",
    "JAY": "Blue bird",
    "JOG": "Slow run",
    "JOY": "Delight",
    "KIT": "Set of supplies",
    "LAP": "Track circuit",
    "LAY": "Set down",
    "LIE": "Untruth",
    "LOT": "Parking area",
    "LOW": "Near the ground",
    "MAD": "Angry",
    "MAN": "Adult male",
    "MIX": "Stir together",
    "MOB": "Unruly crowd",
    "MOM": "Mother",
    "MOP": "Floor cleaner",
    "NAP": "Short sleep",
    "NEW": "Brand-spanking fresh",
    "NOD": "Head yes",
    "NOT": "Negative word",
    "NOW": "At this moment",
    "ODD": "Strange",
    "OFF": "Not on",
    "OLD": "Aged",
    "ONE": "Single unit",
    "OUR": "Belonging to us",
    "OUT": "Not in",
    "OWE": "Be in debt",
    "OWN": "Possess",
    "PAD": "Notepad",
    "PAT": "Light tap",
    "PAW": "Animal foot",
    "PAY": "Settle the bill",
    "PIT": "Deep hole",
    "POP": "Soda",
    "PUB": "Tavern",
    "PUG": "Flat-faced dog",
    "PUN": "Wordplay joke",
    "PUP": "Baby dog",
    "RAG": "Cleaning cloth",
    "RAN": "Sprinted, in the past",
    "RAW": "Uncooked",
    "RAY": "Beam of light",
    "RED": "Fire truck shade",
    "RID": "Get free of",
    "RIM": "Outer edge",
    "RIP": "Tear",
    "ROB": "Steal from",
    "ROT": "Decay",
    "RUB": "Massage",
    "RUN": "Move fast on foot",
    "SAD": "Unhappy",
    "SAT": "Took a seat",
    "SAW": "Cutting blade",
    "SAY": "Utter",
    "SEE": "Lay eyes on",
    "SEW": "Use a needle",
    "SHY": "Bashful",
    "SIP": "Small drink",
    "SIT": "Take a chair",
    "SIX": "Half a dozen",
    "SLY": "Crafty",
    "SOB": "Weep loudly",
    "SPY": "Secret agent",
    "SUM": "Total",
    "TAN": "Sun-kissed shade",
    "TAP": "Faucet",
    "TEN": "Fingers on two hands",
    "TRY": "Attempt",
    "TWO": "A pair",
    "USE": "Put to work",
    "VAT": "Big tub",
    "WAG": "Tail motion",
    "WAY": "Route",
    "WET": "Soaked",
    "WIN": "Take first place",
    "WIT": "Quick humor",
    "WOK": "Stir-fry pan",
    "WON": "Came in first",
    "YAM": "Sweet potato",
    "YES": "Affirmative",
    "YET": "So far",
    "ZAP": "Hit with a jolt",
    "ZIP": "Fastener on a jacket",

    # --- 4 letters: A-L ---
    "ACHE": "Dull throb",
    "ACID": "Sour chemical",
    "ACRE": "Land measure",
    "AREA": "Region",
    "ARMY": "Ground forces",
    "ATOM": "Tiny building block",
    "AUNT": "Parent's sister",
    "AUTO": "Car, informally",
    "BABY": "Newborn",
    "BAIT": "Hook offering",
    "BAKE": "Cook in an oven",
    "BALL": "Round plaything",
    "BAND": "Group of musicians",
    "BANK": "Money keeper",
    "BARN": "Farm building",
    "BASE": "Foundation",
    "BATH": "Tub soak",
    "BEAK": "Bird's bill",
    "BEAN": "Pod vegetable",
    "BEAR": "Forest mammal",
    "BEEF": "Cattle meat",
    "BEER": "Brewed drink",
    "BELL": "It rings",
    "BELT": "Waist strap",
    "BEND": "Curve",
    "BEST": "Top rated",
    "BIKE": "Two-wheeled ride",
    "BIRD": "Feathered flier",
    "BITE": "Chomp",
    "BLUE": "Sky shade",
    "BOAT": "Water vessel",
    "BODY": "Physical form",
    "BOLT": "Metal fastener",
    "BONE": "Skeleton part",
    "BOOK": "Bound pages",
    "BOOT": "Tall shoe",
    "BOWL": "Soup dish",
    "BULB": "Lamp insert",
    "BURN": "Scorch",
    "BUSY": "Not free",
    "CAFE": "Coffee shop",
    "CAGE": "Animal enclosure",
    "CAKE": "Candled dessert",
    "CALM": "Untroubled",
    "CAMP": "Tent stay",
    "CARD": "Deck member",
    "CART": "Shopping wheeler",
    "CASH": "Paper money",
    "CAVE": "Hillside hollow",
    "CELL": "Basic unit of life",
    "CHAT": "Casual talk",
    "CHEF": "Kitchen boss",
    "CHIN": "Under the mouth",
    "CITY": "Urban center",
    "CLAY": "Pottery material",
    "CLUB": "Social group",
    "CLUE": "Hint",
    "COAL": "Black fuel",
    "COAT": "Winter wear",
    "CODE": "Programmer's output",
    "COIN": "Pocket change",
    "COLD": "Chilly",
    "COOK": "Prepare food",
    "COPY": "Duplicate",
    "CORD": "Thin rope",
    "CORN": "Cob crop",
    "COST": "Price",
    "CREW": "Ship's team",
    "CROP": "Farm yield",
    "CUBE": "Six-sided shape",
    "CURL": "Ringlet",
    "DARK": "Without light",
    "DATA": "Information",
    "DAWN": "Daybreak",
    "DEAL": "Bargain",
    "DEEP": "Far down",
    "DEER": "Antlered animal",
    "DESK": "Office furniture",
    "DIAL": "Clock face",
    "DIET": "Eating plan",
    "DIRT": "Soil",
    "DISH": "Plate",
    "DOCK": "Boat landing",
    "DOOR": "Entryway",
    "DRAW": "Sketch",
    "DROP": "Let fall",
    "DRUM": "Percussion instrument",
    "DUCK": "Pond bird",
    "DUSK": "Twilight",
    "DUST": "Fine particles",
    "EACH": "Every one",
    "EARN": "Get paid",
    "EAST": "Sunrise direction",
    "EASY": "Not hard",
    "EDGE": "Border",
    "EPIC": "Grand in scale",
    "EVEN": "Level",
    "EXAM": "Test",
    "EXIT": "Way out",
    "FACE": "Front of the head",
    "FACT": "True statement",
    "FAIR": "Just",
    "FARM": "Crop land",
    "FAST": "Quick",
    "FEAR": "Dread",
    "FILE": "Folder's contents",
    "FILM": "Movie",
    "FIRE": "Flames",
    "FISH": "Gill breather",
    "FIST": "Closed hand",
    "FIVE": "Fingers on a hand",
    "FLAG": "Pole banner",
    "FLAT": "Smooth and level",
    "FOAM": "Bubbles",
    "FOLD": "Crease",
    "FOOD": "Meal fuel",
    "FOOT": "Ankle's neighbor",
    "FORK": "Tined utensil",
    "FORM": "Shape",
    "FREE": "No charge",
    "FROG": "Pond hopper",
    "FUEL": "Tank filler",
    "GAME": "Contest",
    "GATE": "Fence opening",
    "GEAR": "Equipment",
    "GIFT": "Present",
    "GIRL": "Young female",
    "GLOW": "Soft light",
    "GLUE": "Sticky stuff",
    "GOAL": "Aim",
    "GOAT": "Bleating animal",
    "GOLD": "Precious metal",
    "GOLF": "Course sport",
    "GRID": "Network of lines",
    "GRIN": "Wide smile",
    "HAIL": "Ice pellets",
    "HAIR": "Head growth",
    "HALF": "Fifty percent",
    "HALL": "Corridor",
    "HAND": "Five fingers",
    "HARD": "Difficult",
    "HARM": "Damage",
    "HAWK": "Sharp-eyed bird",
    "HEAD": "Top of the body",
    "HEAL": "Get better",
    "HEAP": "Pile",
    "HEAT": "Warmth",
    "HEEL": "Back of the foot",
    "HELP": "Assist",
    "HERB": "Kitchen seasoning",
    "HERD": "Cattle group",
    "HERO": "Brave figure",
    "HIDE": "Conceal",
    "HIGH": "Way up",
    "HIKE": "Trail walk",
    "HILL": "Small rise",
    "HINT": "Nudge in the right direction",
    "HIVE": "Bee home",
    "HOLE": "Opening",
    "HOME": "Where you live",
    "HOOK": "Fishing bend",
    "HOPE": "Wish for",
    "HORN": "Trumpet blast",
    "HOST": "Party giver",
    "HOUR": "Sixty minutes",
    "HUGE": "Enormous",
    "HUNT": "Search",
    "ICON": "Screen symbol",
    "IDEA": "Brainstorm result",
    "INCH": "Twelve to a foot",
    "IRON": "Wrinkle remover",
    "ITEM": "Thing on a list",
    "JAZZ": "Improvised music",
    "JOKE": "Punchline setup",
    "JUMP": "Leap",
    "JURY": "Twelve in a box",
    "KEEN": "Eager",
    "KEEP": "Retain",
    "KICK": "Foot strike",
    "KIND": "Considerate",
    "KING": "Crowned ruler",
    "KITE": "Wind flier",
    "KNEE": "Leg joint",
    "KNOT": "Rope tie",
    "LACE": "Shoe string",
    "LAKE": "Inland water",
    "LAMB": "Young sheep",
    "LAMP": "Table light",
    "LAND": "Dry ground",
    "LANE": "Narrow road",
    "LAST": "Final",
    "LATE": "Not on time",
    "LAVA": "Volcano flow",
    "LAWN": "Mowed grass",
    "LAZY": "Not working",
    "LEAF": "Tree growth",
    "LEAK": "Slow drip",
    "LEAN": "Tilt",
    "LEAP": "Jump",
    "LENS": "Camera glass",
    "LIFE": "Existence",
    "LIFT": "Raise",
    "LIME": "Green citrus",
    "LINE": "Straight mark",
    "LINK": "Chain part",
    "LION": "Maned big cat",
    "LIST": "Itemized rundown",
    "LOAD": "Cargo",
    "LOAF": "Bread unit",
    "LOAN": "Borrowed money",
    "LOCK": "Key's target",
    "LOGO": "Brand mark",
    "LONG": "Not short",
    "LOOK": "Glance",
    "LOOP": "Closed curve",
    "LOST": "Not found",
    "LOUD": "High volume",
    "LUCK": "Chance",
    "LUNG": "Breathing organ",

    # --- 4 letters: M-Z ---
    "MAIL": "Post",
    "MAIN": "Primary",
    "MAKE": "Create",
    "MALL": "Shopping center",
    "MANY": "Numerous",
    "MASK": "Face cover",
    "MAZE": "Puzzle of paths",
    "MEAL": "Breakfast or dinner",
    "MEAT": "Butcher's goods",
    "MELT": "Turn to liquid",
    "MENU": "Dining list",
    "MILD": "Not spicy",
    "MILE": "5,280 feet",
    "MILK": "Dairy drink",
    "MIND": "Seat of thought",
    "MINE": "Ore source",
    "MINT": "Cool herb",
    "MIST": "Fine spray",
    "MOON": "Night orb",
    "MOSS": "Damp green growth",
    "MOTH": "Lamp circler",
    "MOVE": "Shift",
    "NAIL": "Hammer target",
    "NAME": "What you're called",
    "NAVY": "Sea force",
    "NEAR": "Close by",
    "NEAT": "Tidy",
    "NECK": "Head support",
    "NEED": "Require",
    "NEST": "Bird's home",
    "NEWS": "Headlines",
    "NEXT": "Following",
    "NINE": "One less than ten",
    "NODE": "Network point",
    "NOON": "Midday",
    "NOSE": "Smeller",
    "NOTE": "Brief message",
    "NOUN": "Person, place, or thing",
    "OATH": "Solemn promise",
    "OPEN": "Not shut",
    "OVAL": "Egg shape",
    "OVEN": "Baking box",
    "PACK": "Bundle",
    "PAGE": "Book sheet",
    "PAIN": "Hurting",
    "PAIR": "Two of a kind",
    "PALM": "Tropical tree",
    "PARK": "Green public space",
    "PART": "Piece",
    "PAST": "Bygone times",
    "PATH": "Trail",
    "PEAK": "Mountain top",
    "PEAR": "Bell-shaped fruit",
    "PILE": "Stack",
    "PINE": "Evergreen",
    "PINK": "Pale red",
    "PIPE": "Plumbing tube",
    "PLAN": "Strategy",
    "PLAY": "Have fun",
    "PLOT": "Story line",
    "PLUG": "Outlet filler",
    "PLUM": "Purple stone fruit",
    "POEM": "Verse",
    "POLE": "Long rod",
    "POND": "Small lake",
    "PONY": "Small horse",
    "POOL": "Swimming spot",
    "PORT": "Harbor",
    "POST": "Sign holder",
    "PUMP": "Tire inflator",
    "PURE": "Unmixed",
    "PUSH": "Shove",
    "QUIZ": "Short test",
    "RACE": "Speed contest",
    "RAFT": "Inflatable float",
    "RAIN": "Wet weather",
    "RAMP": "Sloped path",
    "RARE": "Uncommon",
    "RATE": "Charge per unit",
    "READ": "Take in a book",
    "REAL": "Genuine",
    "REEF": "Coral ridge",
    "REST": "Take a break",
    "RICE": "Grain staple",
    "RICH": "Wealthy",
    "RIDE": "Go by car",
    "RING": "Finger band",
    "RISE": "Go up",
    "RISK": "Gamble",
    "ROAD": "Paved route",
    "ROAR": "Lion sound",
    "ROBE": "Loose dressing gown",
    "ROCK": "Stone",
    "ROLE": "Actor's part",
    "ROLL": "Bread bun",
    "ROOF": "House top",
    "ROOM": "Indoor space",
    "ROOT": "Plant's anchor",
    "ROPE": "Thick cord",
    "ROSE": "Thorny flower",
    "RUST": "Orange decay on iron",
    "SAFE": "Out of danger",
    "SAIL": "Boat's cloth",
    "SALT": "Pepper's partner",
    "SAND": "Beach grains",
    "SAVE": "Keep for later",
    "SEAL": "Arctic swimmer",
    "SEAT": "Place to sit",
    "SEED": "Plant starter",
    "SEEK": "Look for",
    "SELL": "Trade for money",
    "SEND": "Dispatch",
    "SHED": "Garden building",
    "SHIP": "Ocean vessel",
    "SHOE": "Foot wear",
    "SHOP": "Small store",
    "SHOW": "Display",
    "SIDE": "Flank",
    "SIGN": "Posted notice",
    "SILK": "Smooth fabric",
    "SING": "Carry a tune",
    "SINK": "Kitchen basin",
    "SIZE": "Dimension",
    "SKIN": "Body covering",
    "SKIP": "Leave out",
    "SLED": "Snow ride",
    "SLOW": "Not fast",
    "SNOW": "Winter flakes",
    "SOAP": "Wash bar",
    "SOFA": "Living room seat",
    "SOFT": "Not firm",
    "SOIL": "Garden dirt",
    "SOLO": "On your own",
    "SONG": "Tune",
    "SOON": "Before long",
    "SORT": "Arrange",
    "SOUP": "Bowl dish",
    "STAR": "Night twinkler",
    "STEM": "Flower stalk",
    "STEP": "Stair",
    "STIR": "Mix with a spoon",
    "STOP": "Halt",
    "SUIT": "Jacket and pants",
    "SWIM": "Do laps",
    "TAIL": "Rear appendage",
    "TAKE": "Grab",
    "TALE": "Story",
    "TALK": "Speak",
    "TALL": "Of great height",
    "TANK": "Water container",
    "TAPE": "Sticky roll",
    "TASK": "Chore",
    "TAXI": "Hailed ride",
    "TEAM": "Squad",
    "TEAR": "Rip",
    "TENT": "Camping shelter",
    "TEST": "Quiz",
    "TEXT": "Written words",
    "THIN": "Not thick",
    "TIDE": "Ocean's rise and fall",
    "TIME": "Clock measure",
    "TINY": "Very small",
    "TIRE": "Wheel rubber",
    "TOAD": "Warty hopper",
    "TOOL": "Hammer or wrench",
    "TOWN": "Small city",
    "TREE": "Trunk and branches",
    "TRIM": "Cut back",
    "TRIP": "Journey",
    "TRUE": "Not false",
    "TUBA": "Big brass horn",
    "TUBE": "Hollow cylinder",
    "TUNA": "Sandwich fish",
    "TUNE": "Melody",
    "TURN": "Rotate",
    "TWIN": "Identical sibling",
    "UNIT": "Single measure",
    "VASE": "Flower holder",
    "VAST": "Immense",
    "VEIN": "Blood vessel",
    "VIEW": "Scenery",
    "VINE": "Climbing plant",
    "VOTE": "Cast a ballot",
    "WAGE": "Hourly pay",
    "WAIT": "Hold on",
    "WAKE": "Get up",
    "WALK": "Stroll",
    "WALL": "Room divider",
    "WARM": "Mildly hot",
    "WASH": "Clean up",
    "WAVE": "Ocean swell",
    "WEAK": "Not strong",
    "WEAR": "Have on",
    "WEED": "Garden pest plant",
    "WEEK": "Seven days",
    "WEST": "Sunset direction",
    "WIDE": "Broad",
    "WIFE": "Married woman",
    "WILD": "Untamed",
    "WIND": "Breeze",
    "WINE": "Grape drink",
    "WING": "Bird's flier",
    "WIRE": "Metal strand",
    "WISE": "Full of wisdom",
    "WISH": "Birthday candle thought",
    "WOLF": "Pack hunter",
    "WOOD": "Lumber",
    "WOOL": "Sheep's coat",
    "WORD": "Dictionary entry",
    "WORK": "Daily grind",
    "WORM": "Soil crawler",
    "YARD": "Three feet",
    "YARN": "Knitting thread",
    "YEAR": "365 days",
    "YOGA": "Mat exercise",
    "ZERO": "Nothing",
    "ZONE": "Designated area",
    "ZOOM": "Speed along",

    # --- 5 letters: A-H ---
    "ABOVE": "Overhead",
    "ACTOR": "Movie performer",
    "ADULT": "Grown-up",
    "AGENT": "Representative",
    "AGREE": "Concur",
    "ALARM": "Wake-up sound",
    "ALBUM": "Record release",
    "ALERT": "Watchful",
    "ALIEN": "Extraterrestrial",
    "ALIVE": "Not dead",
    "ALLOW": "Permit",
    "ALONE": "By oneself",
    "ANGEL": "Winged being",
    "ANGER": "Rage",
    "ANGLE": "Corner measure",
    "ANGRY": "Furious",
    "APPLE": "Orchard fruit",
    "APRON": "Cook's cover",
    "ARENA": "Sports venue",
    "ARROW": "Bow's partner",
    "AUDIO": "Sound portion",
    "AWARD": "Prize",
    "AWARE": "Conscious of",
    "BACON": "Breakfast strips",
    "BADGE": "Officer's emblem",
    "BAKER": "Bread maker",
    "BASIC": "Stripped down",
    "BEACH": "Sandy shore",
    "BEGIN": "Start",
    "BELOW": "Underneath",
    "BENCH": "Park seat",
    "BERRY": "Small juicy fruit",
    "BIRTH": "Arrival into the world",
    "BLACK": "Darkest shade",
    "BLADE": "Knife's cutter",
    "BLANK": "Unfilled",
    "BLAST": "Explosion",
    "BLEND": "Mix together",
    "BLOCK": "City stretch",
    "BLOOM": "Flower opening",
    "BOARD": "Wooden plank",
    "BONUS": "Extra reward",
    "BOOST": "Lift up",
    "BRAIN": "Skull's contents",
    "BRAND": "Trademark",
    "BRASS": "Horn metal",
    "BRAVE": "Courageous",
    "BREAD": "Bakery loaf",
    "BREAK": "Snap",
    "BRICK": "Wall block",
    "BRIEF": "Short and to the point",
    "BRING": "Carry along",
    "BROAD": "Very wide",
    "BROOM": "Sweeping tool",
    "BROWN": "Chocolate shade",
    "BRUSH": "Painter's tool",
    "BUILD": "Construct",
    "BUNCH": "Cluster",
    "CABIN": "Log house",
    "CABLE": "Thick wire",
    "CANDY": "Sweet treat",
    "CANOE": "Paddled boat",
    "CARGO": "Freight",
    "CARRY": "Tote",
    "CATCH": "Snag",
    "CHAIN": "Linked metal",
    "CHAIR": "Table's companion",
    "CHALK": "Blackboard writer",
    "CHARM": "Appeal",
    "CHART": "Graph",
    "CHASE": "Pursue",
    "CHEAP": "Low priced",
    "CHECK": "Verify",
    "CHEEK": "Face side",
    "CHEER": "Root for",
    "CHESS": "Game with kings",
    "CHEST": "Torso front",
    "CHIEF": "Top leader",
    "CHILD": "Little one",
    "CHILL": "Cool down",
    "CHOIR": "Singing group",
    "CIVIL": "Polite",
    "CLAIM": "Assert",
    "CLASS": "School group",
    "CLEAN": "Spotless",
    "CLEAR": "See-through",
    "CLIFF": "Steep drop",
    "CLIMB": "Scale a wall",
    "CLOCK": "Time teller",
    "CLOSE": "Shut",
    "CLOTH": "Fabric",
    "CLOUD": "Sky puff",
    "CLOWN": "Circus figure",
    "COACH": "Team leader",
    "COAST": "Shoreline",
    "COLOR": "Hue",
    "COMET": "Tailed space rock",
    "COMIC": "Amusing",
    "CORAL": "Reef builder",
    "COUCH": "Long seat",
    "COUGH": "Throat clearing",
    "COUNT": "Tally up",
    "COURT": "Tennis surface",
    "COVER": "Lid",
    "CRAFT": "Handmade skill",
    "CRANE": "Lifting machine",
    "CRASH": "Collision",
    "CRAZY": "Wildly odd",
    "CREAM": "Dairy topping",
    "CRISP": "Crunchy",
    "CROSS": "Intersect",
    "CROWD": "Many people",
    "CROWN": "Royal headwear",
    "CURVE": "Arc",
    "CYCLE": "Repeating round",
    "DAILY": "Every day",
    "DANCE": "Move to music",
    "DEBUT": "First appearance",
    "DELAY": "Hold up",
    "DELTA": "River mouth",
    "DEPTH": "How far down",
    "DIARY": "Personal journal",
    "DINER": "Roadside eatery",
    "DIRTY": "Unclean",
    "DOUBT": "Uncertainty",
    "DOZEN": "Twelve",
    "DRAFT": "Rough version",
    "DRAIN": "Sink hole",
    "DRAMA": "Theater genre",
    "DRAWN": "Pulled",
    "DREAM": "Sleep vision",
    "DRESS": "Hemmed garment",
    "DRIFT": "Float along",
    "DRILL": "Boring tool",
    "DRINK": "Beverage",
    "DRIVE": "Operate a car",
    "EAGER": "Raring to go",
    "EAGLE": "National bird",
    "EARLY": "Ahead of time",
    "EARTH": "Our planet",
    "EIGHT": "Octopus arm count",
    "ELBOW": "Arm joint",
    "EMPTY": "Vacant",
    "ENJOY": "Take pleasure in",
    "ENTER": "Go in",
    "EQUAL": "The same",
    "ERROR": "Mistake",
    "EVENT": "Happening",
    "EVERY": "Each one",
    "EXACT": "Precise",
    "EXTRA": "Additional",
    "FAINT": "Barely there",
    "FAITH": "Belief",
    "FALSE": "Untrue",
    "FANCY": "Elaborate",
    "FENCE": "Yard border",
    "FERRY": "Passenger boat",
    "FEVER": "High temperature",
    "FIBER": "Dietary roughage",
    "FIELD": "Open land",
    "FIFTY": "Half a hundred",
    "FIGHT": "Brawl",
    "FINAL": "Very last",
    "FIRST": "Number one",
    "FLAME": "Fire's tongue",
    "FLASH": "Quick burst of light",
    "FLEET": "Ship group",
    "FLOAT": "Stay atop water",
    "FLOOD": "Water overflow",
    "FLOOR": "What you stand on",
    "FLOUR": "Baking basic",
    "FLUID": "Liquid",
    "FOCUS": "Sharpen up",
    "FORCE": "Push or pull",
    "FOUND": "Discovered",
    "FRAME": "Picture border",
    "FRESH": "Just made",
    "FRUIT": "Apple or pear",
    "FUNNY": "Humorous",
    "GENRE": "Category of art",
    "GHOST": "Spooky spirit",
    "GIANT": "Very large",
    "GLASS": "Window material",
    "GLOBE": "World sphere",
    "GLOVE": "Hand warmer",
    "GOOSE": "Honking bird",
    "GRACE": "Elegance",
    "GRADE": "School mark",
    "GRAIN": "Wheat kernel",
    "GRAND": "Impressive",
    "GRAPE": "Vine fruit",
    "GRASS": "Lawn cover",
    "GRAVE": "Deadly serious",
    "GREAT": "Excellent",
    "GREEN": "Lawn shade",
    "GROUP": "Collection",
    "GUARD": "Protector",
    "GUESS": "Estimate",
    "GUEST": "Visitor",
    "GUIDE": "Tour leader",
    "HABIT": "Routine",
    "HAPPY": "Cheerful",
    "HARSH": "Severe",
    "HEART": "Blood pump",
    "HEAVY": "Weighty",
    "HEDGE": "Shrub row",
    "HELLO": "Greeting",
    "HONEY": "Bee product",
    "HORSE": "Stable animal",
    "HOTEL": "Lodging",
    "HOUSE": "Dwelling",
    "HUMAN": "Person",
    "HUMOR": "Comedy",

    # --- 5 letters: I-R ---
    "IMAGE": "Picture",
    "INDEX": "Book's back list",
    "INNER": "On the inside",
    "INPUT": "Data entered",
    "ISSUE": "Problem",
    "JELLY": "Toast spread",
    "JOINT": "Where bones meet",
    "JUDGE": "Court official",
    "JUICE": "Fruit drink",
    "KNIFE": "Cutting tool",
    "KNOCK": "Rap on a door",
    "LABEL": "Package tag",
    "LARGE": "Sizable",
    "LASER": "Focused beam",
    "LATER": "Afterward",
    "LAUGH": "Chuckle",
    "LAYER": "One of many levels",
    "LEARN": "Pick up knowledge",
    "LEAVE": "Depart",
    "LEGAL": "Lawful",
    "LEMON": "Sour citrus",
    "LEVEL": "Perfectly flat",
    "LIGHT": "Not heavy",
    "LIMIT": "Boundary",
    "LINEN": "Bed fabric",
    "LOCAL": "Nearby",
    "LODGE": "Ski cabin",
    "LOGIC": "Reasoning",
    "LOOSE": "Not tight",
    "LOWER": "Bring down",
    "LOYAL": "Faithful",
    "LUCKY": "Fortunate",
    "LUNCH": "Midday meal",
    "MAGIC": "Illusion",
    "MAJOR": "Most important",
    "MAKER": "Creator",
    "MAPLE": "Syrup tree",
    "MARCH": "Parade step",
    "MATCH": "Fire starter",
    "MAYBE": "Perhaps",
    "MEDAL": "Winner's award",
    "MEDIA": "The press",
    "METAL": "Iron or steel",
    "MIGHT": "Strength",
    "MINOR": "Not important",
    "MODEL": "Scale replica",
    "MONEY": "Currency",
    "MONTH": "Calendar span",
    "MOTOR": "Engine",
    "MOUNT": "Climb onto",
    "MOUSE": "Small rodent",
    "MOUTH": "Where food goes",
    "MOVIE": "Feature film",
    "MUSIC": "Melody and rhythm",
    "NERVE": "Signal carrier",
    "NEVER": "Not once",
    "NIGHT": "After dark",
    "NOBLE": "High-minded",
    "NOISE": "Racket",
    "NORTH": "Compass point",
    "NOVEL": "Long story",
    "NURSE": "Hospital worker",
    "OCEAN": "Vast body of water",
    "OFFER": "Propose",
    "OFTEN": "Frequently",
    "OLIVE": "Martini garnish",
    "ONION": "Layered bulb",
    "OPERA": "Sung drama",
    "ORBIT": "Circling path",
    "ORDER": "Sequence",
    "ORGAN": "Heart or liver",
    "OTHER": "The different one",
    "OUTER": "External",
    "OWNER": "Possessor",
    "PAINT": "Wall coating",
    "PANEL": "Flat board",
    "PANIC": "Sudden fear",
    "PAPER": "Writing sheet",
    "PARTY": "Celebration",
    "PASTA": "Noodle dish",
    "PATCH": "Mend",
    "PAUSE": "Brief stop",
    "PEACE": "Absence of war",
    "PEACH": "Fuzzy fruit",
    "PEARL": "Oyster gem",
    "PEDAL": "Bike part",
    "PENNY": "One cent",
    "PHONE": "Calling device",
    "PHOTO": "Snapshot",
    "PIANO": "Keyboard instrument",
    "PIECE": "Portion",
    "PILOT": "Plane flier",
    "PITCH": "Throw hard",
    "PIXEL": "Screen dot",
    "PLACE": "Location",
    "PLAIN": "Undecorated",
    "PLANE": "Jetliner",
    "PLANT": "Garden growth",
    "PLATE": "Dinner dish",
    "POINT": "Sharp tip",
    "POLAR": "Arctic",
    "POUND": "Sixteen ounces",
    "POWER": "Energy",
    "PRESS": "Push down on",
    "PRICE": "What you pay",
    "PRIDE": "Self respect",
    "PRIME": "Top quality",
    "PRINT": "Put on paper",
    "PRIZE": "Contest reward",
    "PROUD": "Pleased with yourself",
    "PROVE": "Demonstrate",
    "PULSE": "Heartbeat",
    "PUNCH": "Party drink",
    "PUPIL": "Student",
    "PUPPY": "Young dog",
    "PURSE": "Handbag",
    "QUEEN": "Royal woman",
    "QUICK": "Speedy",
    "QUIET": "Silent",
    "QUILT": "Patchwork blanket",
    "QUOTE": "Cited words",
    "RADAR": "Detection system",
    "RADIO": "Airwave receiver",
    "RAINY": "Drizzly",
    "RAISE": "Hoist",
    "RANCH": "Cattle spread",
    "RANGE": "Extent",
    "RAPID": "Very fast",
    "RATIO": "Proportion",
    "REACH": "Extend to",
    "READY": "Prepared",
    "RIDER": "Horse sitter",
    "RIDGE": "Long crest",
    "RIGHT": "Correct",
    "RIVAL": "Competitor",
    "RIVER": "Flowing water",
    "ROAST": "Cook in the oven",
    "ROBOT": "Machine worker",
    "ROCKY": "Full of stones",
    "ROUGH": "Not smooth",
    "ROUND": "Circular",
    "ROUTE": "Path taken",
    "ROYAL": "Kingly",
    "RULER": "Measuring stick",

    # --- 5 letters: S-Z ---
    "SALAD": "Greens bowl",
    "SALTY": "Briny",
    "SANDY": "Like a beach",
    "SAUCE": "Pasta topping",
    "SCALE": "Weighing device",
    "SCARF": "Neck wrap",
    "SCENE": "Movie segment",
    "SCENT": "Aroma",
    "SCORE": "Game tally",
    "SCOUT": "Advance searcher",
    "SENSE": "Sight or smell",
    "SERVE": "Dish out",
    "SEVEN": "Days in a week",
    "SHADE": "Shadow",
    "SHAKE": "Jiggle",
    "SHAPE": "Form",
    "SHARE": "Divide up",
    "SHARK": "Ocean predator",
    "SHARP": "Keen-edged",
    "SHEEP": "Wool source",
    "SHEET": "Bed cover",
    "SHELF": "Book holder",
    "SHELL": "Beach find",
    "SHIFT": "Work stint",
    "SHINE": "Gleam",
    "SHINY": "Reflective",
    "SHIRT": "Torso wear",
    "SHOCK": "Jolt",
    "SHORE": "Water's edge",
    "SHORT": "Lacking height",
    "SHOUT": "Yell",
    "SIGHT": "Vision",
    "SILLY": "Goofy",
    "SINCE": "From then on",
    "SIXTY": "Minutes in an hour",
    "SKATE": "Ice glider",
    "SKILL": "Ability",
    "SKIRT": "Below-the-waist wear",
    "SLEEP": "Nightly rest",
    "SLICE": "Cut piece",
    "SLIDE": "Playground feature",
    "SLOPE": "Incline",
    "SMALL": "Little",
    "SMART": "Clever",
    "SMELL": "Odor",
    "SMILE": "Upturned mouth",
    "SMOKE": "Fire's plume",
    "SNACK": "Light bite",
    "SNAIL": "Slow shell carrier",
    "SNAKE": "Slithering reptile",
    "SOLAR": "Sun-powered",
    "SOLID": "Firm",
    "SOLVE": "Work out",
    "SOUND": "What you hear",
    "SOUTH": "Below the equator",
    "SPACE": "The final frontier",
    "SPARK": "Tiny flash",
    "SPEAK": "Say something",
    "SPEED": "Velocity",
    "SPELL": "Name the letters of",
    "SPEND": "Pay out",
    "SPICE": "Seasoning",
    "SPINE": "Backbone",
    "SPLIT": "Divide",
    "SPORT": "Athletic game",
    "SPRAY": "Fine mist",
    "SQUAD": "Small team",
    "STACK": "Pile up",
    "STAFF": "Employees",
    "STAGE": "Theater platform",
    "STAIR": "One of a flight",
    "STAMP": "Envelope sticker",
    "STAND": "Get on your feet",
    "STARE": "Gaze",
    "START": "Get going",
    "STATE": "One of fifty",
    "STEAM": "Hot vapor",
    "STEEL": "Strong alloy",
    "STEEP": "Sharply sloped",
    "STICK": "Twig",
    "STILL": "Motionless",
    "STING": "Bee's jab",
    "STOCK": "Company share",
    "STONE": "Boulder bit",
    "STORE": "Retail spot",
    "STORM": "Tempest",
    "STORY": "Narrative",
    "STOVE": "Cooking range",
    "STUDY": "Hit the books",
    "STYLE": "Fashion sense",
    "SUGAR": "Sweetener",
    "SUNNY": "Cloudless",
    "SUPER": "Terrific",
    "SWEEP": "Broom work",
    "SWEET": "Sugary",
    "SWIFT": "Moving fast",
    "SWING": "Playground seat",
    "TABLE": "Dining furniture",
    "TASTE": "Flavor",
    "TEACH": "Instruct",
    "TEETH": "Mouth grinders",
    "TENTH": "After ninth",
    "THANK": "Express gratitude to",
    "THEME": "Central idea",
    "THICK": "Not slim",
    "THIEF": "Robber",
    "THING": "Object",
    "THINK": "Use your brain",
    "THIRD": "After second",
    "THREE": "Trio count",
    "THROW": "Toss",
    "THUMB": "Hand digit",
    "TIGER": "Striped cat",
    "TIGHT": "Snug",
    "TIMER": "Countdown device",
    "TITLE": "Book name",
    "TOAST": "Browned bread",
    "TODAY": "This very day",
    "TOKEN": "Arcade coin",
    "TOOTH": "Molar",
    "TOPIC": "Subject",
    "TORCH": "Handheld flame",
    "TOTAL": "Sum",
    "TOUCH": "Feel",
    "TOUGH": "Hard to chew",
    "TOWEL": "Drying cloth",
    "TOWER": "Tall structure",
    "TOXIC": "Poisonous",
    "TRACE": "Faint mark",
    "TRACK": "Running oval",
    "TRADE": "Swap",
    "TRAIL": "Hiking path",
    "TRAIN": "Rail transport",
    "TRASH": "Garbage",
    "TREAT": "Goodie",
    "TREND": "Current fashion",
    "TRIAL": "Court case",
    "TRIBE": "Clan",
    "TRICK": "Prank",
    "TRUCK": "Hauling vehicle",
    "TRUNK": "Tree's main stem",
    "TRUST": "Rely on",
    "TRUTH": "What's real",
    "TULIP": "Spring bulb flower",
    "TWICE": "Two times",
    "TWIST": "Turn sharply",
    "UNCLE": "Parent's brother",
    "UNDER": "Beneath",
    "UNION": "Workers' group",
    "UNITE": "Join together",
    "UNTIL": "Up to the time of",
    "UPPER": "Higher of two",
    "URBAN": "City-related",
    "USUAL": "Customary",
    "VALUE": "Worth",
    "VAPOR": "Gas form",
    "VAULT": "Bank's strong room",
    "VENUE": "Event site",
    "VERSE": "Poem section",
    "VIDEO": "Recording to watch",
    "VIRUS": "Tiny germ",
    "VISIT": "Drop by",
    "VITAL": "Essential",
    "VIVID": "Bright and clear",
    "VOICE": "Vocal sound",
    "VOTER": "Ballot caster",
    "VOWEL": "A, E, I, O, or U",
    "WAGON": "Pulled cart",
    "WAIST": "Belt line",
    "WASTE": "Squander",
    "WATCH": "Wrist timepiece",
    "WATER": "H2O",
    "WEAVE": "Work a loom",
    "WEDGE": "Tapered block",
    "WHALE": "Ocean giant",
    "WHEAT": "Bread grain",
    "WHEEL": "Round roller",
    "WHERE": "In what place",
    "WHICH": "What one",
    "WHILE": "During",
    "WHITE": "Snow shade",
    "WHOLE": "Entire",
    "WIDTH": "How wide",
    "WOMAN": "Adult female",
    "WORLD": "The globe",
    "WORRY": "Fret",
    "WORSE": "Less good",
    "WORTH": "Value",
    "WOUND": "Injury",
    "WRIST": "Hand joint",
    "WRITE": "Put down on paper",
    "WRONG": "Incorrect",
    "YACHT": "Luxury boat",
    "YEAST": "Bread riser",
    "YIELD": "Give way",
    "YOUNG": "Not old",
    "YOUTH": "Early years",
    "ZEBRA": "Striped animal",
}

